blog/urls.py
from django.conf.urls import url, include, patterns

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^news/$', views.xxx, name='xxx'),
    url(r'^articles/(?P<article_id>[0-9]+)/$', views.show_article, name='article'),
    url(r'^partner/(?P<partner_id>[0-9]+)/$', views.about, name='partners'),
    url(r'^thanks/$', views.thenks, name='thenks'),
    url(r'^simpleform/$', views.mysimpleform, name='form'),
    url(r'^userlogin/$', views.userauth, name = 'userlogin'),
    url(r'^userlogout/$', views.logout_view, name= 'logout'),
    url(r'^complete/$', views.thenksshop, name='complete')
]

laserSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.forms import RegistrationForm
from registration.views import RegistrationView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


register = RegistrationView.as_view()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.urls', namespace="registration")),
    url(r'^accounts/register/$', register, {
        'form_class': RegistrationForm,
        'backend': 'registration.backends.default.DefaultBackend'},),
    url('', include('registration.urls')),
    url(r'^', include('blog.urls')),
    url(r'^photologue/', include('photologue.urls', namespace="photologue")),
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name='homepage'),
    url(r'^shop/', include('magaz.urls')),
    url(r'^cart/', include('cart1.urls', namespace='cart1')),
    url(r'^redactor/', include('redactor.urls', namespace='redactor' )),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/backends/simple/urls.py
"""
URLconf for registration using django-registration's simple one-step
workflow.

"""

from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from .views import RegistrationView


urlpatterns = [
    url(r'^register/$',
        RegistrationView.as_view(),
        name='registration_register'),
    url(r'^register/closed/$',
        TemplateView.as_view(
            template_name='registration/registration_closed.html'
        ),
        name='registration_disallowed'),
    url(r'', include('registration.auth_urls')),
]

blog/models.py
import datetime
from redactor.fields import RedactorField

from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models


tweet = 1000

class Article(models.Model):
    title = models.CharField(max_length=200)
    pub_day = models.DateTimeField('pub date')
    text = RedactorField(verbose_name=u'Text',
                         redactor_options={'lang': 'en', 'focus': 'true'},
                         allow_file_upload=False,
                         allow_image_upload=False)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def get_short_text(self):
        if len(self.text) > tweet:
            return self.text[:tweet]
        else:
            return self.text

    def w_p_r(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_day <= now
    w_p_r.admin_order_field = 'pub_date'
    w_p_r.boolean = True
    w_p_r.short_description = 'fresh'

class Partners(models.Model):
    PartnerName = models.CharField(max_length=40)
    PartnerPic = models.ImageField(upload_to='partners/')
    PartnerDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.PartnerName

    class Meta:
        ordering = ['-PartnerDate']

blog/forms.py
from django import forms
from registration.forms import User


class SimpleForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 40, 'class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size': 40, 'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

blog/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from cart1.cart import Cart
from blog.models import Article, Partners
from photologue.models import *
from blog.forms import SimpleForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect


def home(request):
    news = Article.objects.order_by('-pub_day')[:5]
    imgs = Photo.objects.on_site().is_public()[:5]
    cart= Cart(request)
    context={
        'news': news,
        'imgs': imgs,
        'cart': cart
    }
    return render(request, 'blog/home.html', context)


def about(request):
    cart = Cart(request)
    partners = Partners.objects.all()
    form = SimpleForm(request.POST)
    return render(request, 'blog/about.html', {'cart': cart, 'partners': partners, 'form': form})


def show_partners(request, partner_id):
    partner = get_object_or_404(Partners ,id= partner_id)
    return render(request, 'blog/partner.html', {'partner': partner})


def xxx(request):
    articles = Article.objects.order_by('-pub_day')
    cart= Cart(request)
    context={
        'articles': articles,
        'cart': cart,
    }

    return render(request, 'blog/xxx.html', context)


def show_article(request, article_id):
    article = get_object_or_404(Article, id= article_id)
    cart= Cart(request)
    return render(request, 'blog/article.html', {'article': article, 'cart': cart})


def mysimpleform(request):

    if request.method == 'POST':
        form = SimpleForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username'] + ' from ' + str(form.cleaned_data['sender'])
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recipients = ['avi.upsale@gmail.com']

            if copy == True:
                recipients.append(sender)
            try:
                send_mail(username, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('something goes wrong ;(')
            return HttpResponseRedirect('/thanks')

    else:
        form = SimpleForm()
    return render(request, 'blog/simpleform.html', {'form': form, 'username': auth.get_user(request).username})


def thenks(request):
    thenks = 'thenks'
    context = {'thenks': thenks}
    return render(request, 'blog/thenks.html', context)

def userauth(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your sferalaser account is disabled.")
        else:
            print('невірні данні: {0}, {1}'.format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'blog/userlogin.html', {})


def logout_view(request):
    lo = logout(request)
    return render(request, 'blog/logout.html', {'logout': lo})


def thenksshop(request):
    context = {'thenksshop': thenks}
    return render(request, 'blog/thenksshop.html', context)

blog/templates/blog/about.html
{% extends 'magaz/base.html' %}
{% block title %}
Sfera-Laser
{% endblock %}
{% block content %}
    <h1>Sfera-Laser inc.</h1>

    <div class="row">
<div class="col-md-6">
    <div class="contacts">
        <p>Компанія "Сфера-лазер"</p>
        <p>79016 Львів, вул. Шевченко, 20</p>
        <p>(032) 244-57-61, 245-05-52 моб.: 067-49-19-396 </p>
        <p>e-mail:  <a href="mailto:sferalaser@gmail.com">sferalaser@gmail.com</a></p>
    </div>
    <div>
        <iframe id="gmap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2572.9503205020164!2d24.01387431525171!3d49.84339097939623!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473add75d3e4d639%3A0xebd6fc2dba4f91af!2z0KHQpNCV0KDQkC3Qm9CQ0JfQldCgINCa0J7QnNCf0JDQndCG0K8g0KLQntCS!5e0!3m2!1sru!2sua!4v1464072083394" width="450" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>

        <div class="content col-lg-4 col-md-4"  id="simpleform">
<form action="{% url 'form' %}" method="post" id="postform" class="form-horizontal" role="form">{% csrf_token %}
    <h3 id="form_title" >Зворотній зв'язок</h3>
    {{ form.non_field_errors }}
	<div class="form-group">
	  <label id="simpleform username" for="id_subject" >Тема:</label>
	  {{ form.username }}
	</div>
	<div class="form-group">
	  <label for="id_sender" >E-mail:</label>
	  {{ form.sender }}
	</div >
	<div class="form-group">
	  <label for="id_message" >Повідомлення:</label>
        <div id="textbox">
	  {{ form.message }}
        </div>
	</div>
	<div class='form-group'>
	  {{ form.copy.errors }}
	  <label for="id_copy" > {{ form.copy }} Копія на свій e-mail</label>
	</div>
	<input type="submit" value="Відправити"/>
</form>
</div>

</div>

<hr>
<h1>Наші партнери</h1>
    {% for partner in partners %}
    <div class="row col-lg-2">
             <div class="partners">
                 <img src="{{ partner.PartnerPic.url }}" height="100px"  >
                <p>{{ partner.PartnerName }}</p>
             </div>
    </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/article.html
{% extends "magaz/base.html" %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block content %}

    <h1>{{ article.title }}</h1>
    <h3>{{ article.pub_day }}</h3>
    <pre id="pre-home">{{ article.text }}</pre>
    <div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//sferalaser.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
  <head>
  <title>{% block title %}{% endblock %}</title>
      <meta charset="utf-8">
      <meta content="IE=edge" http-equiv="X-UA-Compatible">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

        <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/cyborg/bootstrap.min.css" rel="stylesheet" >
        <link href="{% static 'blog/style.css' %}" rel="stylesheet">

        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">laserSite</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Головна</a></li>
            <li><a href="{% url 'about' %}">Про нас</a></li>
            <li><a href="{% url 'xxx' %}">Блог</a> </li>
            <li><a href="/photologue/">Галерея</a> </li>
            <li><a href="/shop/">Магазин</a> </li>
            <li><a href="/admin/">Одминко</a> </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container main-content">




        {% block content %}
        {% endblock %}
    <div class="foot">
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 Зроблено на Сихові &middot; <a href="#">Андрій Війтик</a> &middot; <a href="#">Сфера-Лазер</a></p>
      </footer>
    </div>


    </div><!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  </body>
</html>

blog/templates/blog/home.html
{% extends "magaz/base.html" %}

{% load staticfiles %}


{% block title %}
Sfera-Laser
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
	<div id="myCarousel" class="carousel  slide">
  <!-- Dot Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Items -->
  <div class="carousel-inner">
    <div class="active item">  <img src="{% static 'blog/1.jpg' %}" class="img-responsive"></div>
    <div class="item">  <img src="{% static 'blog/2.jpg' %}" class="img-responsive"></div>
    <div class="item">  <img src="{% static 'blog/3.jpg' %}" class="img-responsive"></div>
    <div class="item">  <img src='{% static 'blog/4.jpg' %}' class="img-responsive"></div>
  </div>
  <!-- Navigation -->
    </div>
    </div>
    <script>
         $(document).ready(function() {
         $('.carousel').carousel({interval: 4000});
             });
    </script>
    </div>


  <!-- Controls

  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

        -->

     <hr color="#f5f5f5">
        <div class="row">
        <div class="col-lg-4" id="img-f">
          <img class="img-circle" src="{% static 'blog/porezka.jpg' %}" alt="Generic placeholder image" width="200" height="200">
          <h3>Лазерна порізка</h3>
          <h3> </h3>
          <p>Основний напрямок порізки- це лазерна порізка Акрилу(від 1.5 до 10мм), також ми спеціалізуємось на порізці фанери (4-8мм) і поліпропілену. Працюємо як з власними, так і з вашими матеріалами.</p>
          <p><a class="btn btn-primary" href="/photologue/gallery/porizka/" role="button">Альбом в галереї &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4" id="img-f">
          <img class="img-circle" src="{% static 'blog/zippo.jpg' %}" alt="Generic placeholder image" width="200" height="200">
          <h3>Лазерне гравіювання</h3>
          <h3> </h3>
          <p>Завдяки сучасному обладнанню, та профессіанолізму наших працівників ми здійснюємо гравіювання різних видів складності на різних маитеріалах та виробах. А також надаєм послуги кирилізації клавіатур.</p>
          <p><a class="btn btn-primary" href="/photologue/gallery/graviruvannya/" role="button">Свіжі замовлення &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4" id="img-f">
          <img class="img-circle" src="{% static 'blog/rek.jpg' %}" alt="Generic placeholder image" width="200" height="200">
          <h3>Пластикові підставки та торгове обладнання</h3>
          <p> Наші інженери реалізують будь-яку задачу, пов'язану з моделюванням та виробництвом пластикових підставок та торгового обладнання. Також надаєм консультації з дизайну</p>
          <p><a class="btn btn-primary" href="/shop/" role="button">Дізнатись більше &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
    <hr color="white">
    <div class="new_photo">
        <h3 class="n_ph">Наші роботи</h3>
        <div class="row" id="n_p">
		    {% for photo in imgs %}
                <div class="col-md-2">
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
		        </a>
                </div>
		    {% endfor %}
		</div>
    </div>
    <hr>
<div class="news">
<h1>Новини</h1>
<p id="n_t">
    <span> Сайт працює в тестовому режимі з початку літа.</span>
</p>
 <hr color="white">

    {% for article in news %}
    <div class="tit">
        <h4><a href="{% url 'article' article.id %}">{{ article.title }}</a></h4>
        <h5>{{ article.pub_day }}</h5>
    </div>
     <pre id="pre-home">{{ article.get_short_text }}
<a href="{% url 'article' article.id %}" >далі</a></pre>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/logout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
{% extends 'magaz/base.html' %}
{{ logout }}
{% block content %}
    <div class="text-center ">
<h3>Ви вийшли</h3>
        <p>
            <a class="btn btn-primary" href="/">на головну</a>
        </p>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/partner.html
<p>parter_hui1</p>

blog/templates/blog/simpleform.html
{% extends 'magaz/base.html' %}

{% block content %}
        <div class="content col-lg-4 col-md-4"  id="simpleform">
<form action="{% url 'form' %}" method="post" id="postform" class="form-horizontal" role="form">{% csrf_token %}
    <h3 id="form_title" >Зворотній зв'язок</h3>
    {{ form.non_field_errors }}
	<div class="form-group">
	  <label id="simpleform username" for="id_subject" >Тема:</label>
        {{ form.username.errors }}
	  {{ form.username }}
	</div>
	<div class="form-group">
	  <label for="id_sender" >E-mail:</label>
        {{ form.sender.errors }}
	  {{ form.sender }}
	</div >
	<div class="form-group">
	  <label for="id_message" >Повідомлення:</label>
        {{ form.message.errors }}
	  {{ form.message }}
	</div>
	<div class='form-group'>
	  {{ form.copy.errors }}
	  <label for="id_copy" > {{ form.copy }} Копія на свій e-mail</label>
	</div>
	<input type="submit" value="Отправить"/>
</form>
    </div>
{% endblock %}

blog/templates/blog/thenks.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Дякуюємо вам!</title>
</head>
<body>
{% extends 'magaz/base.html' %}
{% block content %}
<div id="thenks">
    <p>Дякуємо за ваше повідомлення, ми з Вами зв'яжемось.</p>
</div>
{% endblock %}
</body>
</html>

blog/templates/blog/thenksshop.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Дякумо!</title>
</head>
<body>
{% extends 'magaz/base.html' %}
{% block content %}
    <div class="text-center">
    <h3>Дякуємо за ваш вибір!</h3>
    <p>Ваше замовлення успішно відправлено. Менеджер зв'яжеться з вами впродовж 30 хв.</p>
    <a class="btn btn-primary" href="/" role="button"> На головну </a>
    </div>

{% endblock %}
</body>
</html>

blog/templates/blog/userlogin.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Авторизація</title>
</head>
<body class="full">
{% extends 'magaz/base.html' %}
{% block content %}
    <h1>Авторизація</h1>
    <form id="centrform" class="col-md-5"  method="post" action="{% url 'userlogin' %}">
            {% csrf_token %}
            <br />
            <input type="text" name="username" placeholder="Ім'я користувача" id="userlogin_username" value=""  size="30" class="form-group" />
            <br />
            <input type="password" name="password" placeholder="Пароль" id="userlogin_password" value="" size="30" class="form-group" />
            <br />
            <input class="btn-success" type="submit" value="Вхід" id="form-button" />
        </form>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/xxx.html
{% extends "magaz/base.html" %}
{% load staticfiles %}

{% block title %}
Новини
{% endblock %}
{% block content %}
<h1>Новини компанії</h1>
    {% for article in articles%}
        <h4><a href="{% url 'article' article.id %}">{{ article.title }}</a></h4>
        <h5>{{ article.pub_day }}</h5>
        <pre id="pre-home">{{ article.get_short_text }}
            <div class="us">
                <p>
                {{ article.user }}
                </p>
            </div>



<a href="{% url 'article' article.id %}" >далі</a></pre>
    {% endfor %}
{% endblock %}