blog/urls.py
from django.conf.urls import url, include, patterns

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^news/$', views.xxx, name='xxx'),
    url(r'^articles/(?P<article_id>[0-9]+)/$', views.show_article, name='article'),
    url(r'^partner/(?P<partner_id>[0-9]+)/$', views.about, name='partners'),
    url(r'^thanks/$', views.thenks, name='thenks'),
    url(r'^simpleform/$', views.mysimpleform, name='form'),
    url(r'^userlogin/$', views.userauth, name = 'userlogin'),
    url(r'^userlogout/$', views.logout_view, name= 'logout'),
    url(r'^complete/$', views.thenksshop, name='complete')
]

cart1/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<good_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<good_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

laserSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.forms import RegistrationForm
from registration.views import RegistrationView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


register = RegistrationView.as_view()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.urls', namespace="registration")),
    url(r'^accounts/register/$', register, {
        'form_class': RegistrationForm,
        'backend': 'registration.backends.default.DefaultBackend'},),
    url('', include('registration.urls')),
    url(r'^', include('blog.urls')),
    url(r'^photologue/', include('photologue.urls', namespace="photologue")),
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name='homepage'),
    url(r'^shop/', include('magaz.urls')),
    url(r'^cart/', include('cart1.urls', namespace='cart1')),
    url(r'^redactor/', include('redactor.urls', namespace='redactor' )),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magaz/urls.py
from django.conf.urls import url, include, patterns

from . import views

urlpatterns = [
    url(r'^cabinet/$', views.cabinet, name='cabinet'),
    url(r'^setuah/$', views.set_uah, name='set_uah'),
    url(r'^setusd/$', views.set_usd, name='set_usd'),
    url(r'^orderform/$', views.orderformr, name='of'),
    url(r'^siteform/$', views.siteform, name='siteform'),
    url(r'^skypeform/$', views.skypeform, name='skypeform'),
    url(r'^professionform/$', views.professionform, name='professionform'),
    url(r'^numbform/$', views.numbform, name='numbform'),
    url(r'^aboutform/$', views.aboutform, name='aboutform'),
    url(r'^avatarform/$', views.avatarform, name='avatarform'),
    url(r'^order/$', views.just_pay_for_all, name='order'),
    url(r'^$', views.shop, name='shop'),
    url(r'product/(?P<good_id>[0-9]+)/$', views.show_goods, name='prises'),
    url(r'(?P<slag_url>[\-\d\w]+)/$', views.cat_detail, name='category'),
]

social/apps/django_app/urls.py
"""URLs module"""
from django.conf import settings
try:
    from django.conf.urls import url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import url

from social.utils import setting_name
from social.apps.django_app import views


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

urlpatterns = [
    # authentication / association
    url(r'^login/(?P<backend>[^/]+){0}$'.format(extra), views.auth,
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), views.complete,
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), views.disconnect,
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+){0}$'
        .format(extra), views.disconnect, name='disconnect_individual'),
]

magaz/forms.py
from django import forms
from magaz.models import *
from magaz.userdata import UserData

#общая "большая" форма
"""
class CabinetForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ('site', 'skype', 'profession', 'numb', 'about', 'avatar')
"""

class SiteMiniForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ('site',)


class SkypeMiniForm(forms.ModelForm):
    class Meta:
        model = SkypeUser
        fields = ('skype',)


class ProfessionMiniForm(forms.ModelForm):
    class Meta:
        model = ProfessionalUser
        fields = ('profession',)


class NumbMiniForm(forms.ModelForm):
    class Meta:
        model = NumbUser
        fields = ('numb',)


class AboutMiniForm(forms.ModelForm):
    class Meta:
        model = AboutUser
        fields = ('about',)


class AvatarMiniForm(forms.ModelForm):
    class Meta:
        model = AvatarUser
        fields = ('avatar',)


class PayGoodForm(forms.ModelForm):
    class Meta:
        model = GoodPay
        fields = []

class ValuteForm(forms.ModelForm):
    class Meta:
        model = Prises
        fields = ()

class HrivnaForm(forms.ModelForm):
    class Meta:
        model = Prises
        fields = ()

class OrderForm(forms.Form):
    ttt = [('самовивіз', 'самовивіз'), ('нова пошта', 'нова пошта')]
    clientname = forms.CharField(required=True, label="Ім'я", widget=forms.TextInput(attrs={'size': 40, 'class': 'form-control'}))
    clientsorganization = forms.CharField(required=False, label="Організація", widget=forms.TextInput(attrs={'size': 40, 'class': 'form-control'}))
    clientsnumb = forms.CharField(required=True, label='Номер Телефону', widget=forms.TextInput(attrs={'size': 40, 'class': 'form-control'}))
    clientmail = forms.CharField(required=False, label='e-mail',
                                 widget=forms.TextInput(attrs={'size': 40, 'class': 'form-control'}))
    clientdevelop = forms.ChoiceField(choices=ttt)
    clientcomment = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))

magaz/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from magaz.forms import *
from magaz.models import Prises, Category, GoodPay
from cart1.forms import CartAddProductsForm
from cart1.cart import Cart
from magaz.userdata import UserData
from django.contrib.auth.models import User



def shop(request):
    categories = Category.objects.order_by('-cat_name')
    goods = Prises.objects.order_by('-good_time')
    cart= Cart(request)
    context = {'categories': categories,
               'goods': goods,
               'cart': cart}
    return render(request, 'magaz/shop1.html', context)      #длля продолжения работы с категориями заменить на шоп1


def cat_detail(request, slag_url):
    category = get_object_or_404(Category, slag_url=slag_url)
    goods = Prises.objects.order_by('-good_time')
    return render(request, 'magaz/cat_detail.html', {'category': category, 'goods': goods, })



def show_goods(request, good_id):
    prices = get_object_or_404(Prises, id=good_id)
    cart_product_form = CartAddProductsForm()
    cart= Cart(request)
    return render(request, 'magaz/good.html', {'prices': prices, 'cart_product_form': cart_product_form, 'cart': cart})


def cabinet(request):
    cabinet = 'cabinet'
    userpay = GoodPay.objects.filter(user=request.user).order_by('-date').values()
    pr = Prises.objects.all().values('id', 'good_name')
    sif = SiteMiniForm(request.POST)
    skf = SkypeMiniForm(request.POST)
    prf = ProfessionMiniForm(request.POST)
    nmf = NumbMiniForm(request.POST)
    abf = AboutMiniForm(request.POST)
    avf = AvatarMiniForm(request.POST)
    return render(request, 'magaz/cabinet.html', {'cabinet': cabinet, 'sif': sif, 'skf': skf, 'prf': prf, 'nmf': nmf,
                                                  'abf': abf, 'avf': avf, 'userpay': userpay, 'pr': pr})


def siteform(request):
    user = request.user
    if request.method == 'POST':
        site_form = SiteMiniForm(request.POST)
        if site_form.is_valid():
            sitesave = site_form.save(commit=False)
            sitesave.user = user
            sitesave.save()
            return HttpResponseRedirect('/shop/cabinet')
    else:
        site_obj = SiteUser.objects.get(user=request.user)
        site_form = SkypeMiniForm(instance= site_obj)
        return render(request, 'magaz/forms/site.html', {'site_form': site_form})


def skypeform(request):
    user = request.user
    if request.method == 'POST':
        skype_form = SkypeMiniForm(request.POST)
        if skype_form.is_valid():
            skypesave = skype_form.save(commit=False)
            skypesave.user = user
            skypesave.save()
            return HttpResponseRedirect('/shop/cabinet')
    else:
        skype_obj = SkypeUser.objects.get(user=request.user)
        skype_form = SkypeMiniForm(instance= skype_obj)
        return render(request, 'magaz/forms/skype.html', {'skype_form': skype_form})


def professionform(request):
    user = request.user
    if request.method == 'POST':
        profession_form = ProfessionMiniForm(request.POST)
        if profession_form.is_valid():
            professionsave = profession_form.save(commit=False)
            professionsave.user = user
            professionsave.save()
            return HttpResponseRedirect('/shop/cabinet')
    else:
        # pro_obj = ProfessionalUser.objects.get(user=request.user)
        profession_form = ProfessionMiniForm()
        return render(request, 'magaz/forms/profess.html', {'profession_form': profession_form})


def numbform(request):
    user = request.user
    if request.method == 'POST':
        numb_form = NumbMiniForm(request.POST)
        if numb_form.is_valid():
            numbsave = numb_form.save(commit=False)
            numbsave.user = user
            numbsave.save()
            return HttpResponseRedirect('/shop/cabinet')
    else:
        numb_form = NumbMiniForm()
        return render(request, 'magaz/forms/numb.html', {'numb_form': numb_form})


def aboutform(request):
    user = request.user
    if request.method == 'POST':
        about_form = AboutMiniForm(request.POST)
        if about_form.is_valid():
            aboutsave = about_form.save(commit=False)
            aboutsave.user = user
            aboutsave.save()
            return HttpResponseRedirect('/shop/cabinet')
    else:
        about_form = AboutMiniForm()
        return render(request, 'magaz/forms/about.html', {'about_form': about_form})

def avatarform(request):
    user = request.user
    if request.method == 'POST':
        avatar_form = AvatarMiniForm(request.POST)
        if avatar_form.is_valid():
            avatarsave = avatar_form.save(commit=False)
            avatarsave.user = user
            if 'avatar' in request.FILES:
                avatarsave.avatar = request.FILES['avatar']
            avatarsave.save()
            return HttpResponseRedirect('/shop/cabinet')
    else:
        avatar_form = AvatarMiniForm()
    return render(request, 'magaz/forms/avatar.html', {'avatar_form': avatar_form})


def just_pay_for_all(request):
    order = 'order'
    user = request.user
    cart = Cart(request)
    of = OrderForm(request.POST)
    if request.method == 'POST':
        form = PayGoodForm(request.POST)
        if form.is_valid():
            formsave = form.save(commit=False)
            formsave.user =user
            for item in cart:
                GoodPay.objects.create(
                    user=user,
                    prises=item['prise'],
                    price=item['good_price'],
                    quantity=item['quantity'],
                    ordersum=int(item['good_price'])*item['quantity']
                )
            cart.clear()
            return HttpResponseRedirect('/')

    else:
        form = PayGoodForm()

    return render(request, 'magaz/order.html', {order: 'order', cart: 'cart', form: 'form',
                                                'of': of})


def set_uah(request):
    val = UserData(request)
    val.setuah()
    return HttpResponseRedirect(request.GET.get('next'))


def set_usd(request):
    val = UserData(request)
    val.setdolar()
    return HttpResponseRedirect(request.GET.get('next'))


def orderformr(request):
    user = request.user
    cart = Cart(request)

    pr = Prises.objects.all().values('id', 'good_name')
    if request.method == 'POST':
        orderform = OrderForm(request.POST)
        form = PayGoodForm(request.POST)
        if orderform.is_valid() and form.is_valid():

            cartinfo  = ''
            for good in cart.cart:
                for dat in pr:
                    if dat['id'] == int(good):
                        cartinfo += str(dat['good_name']) + ' ; ціна за одиницю  ' + str(cart.cart[good]['good_price']) + \
                                    '; кількість: ' + str(cart.cart[good]['quantity']) + ' | '
            username = orderform.cleaned_data['clientname'] + ' from ' + str(orderform.cleaned_data['clientmail'])
            sender = orderform.cleaned_data['clientmail']
            message = 'клієнт: ' + str(orderform.cleaned_data['clientname']) + '; ' + ' Номер телефону: ' + \
                      str(orderform.cleaned_data['clientsnumb']) + '; ' + ' організація: ' + \
                      str(orderform.cleaned_data['clientsorganization']) + '; ' + ' спосіб доставки :' + orderform.cleaned_data['clientdevelop'] +\
                      '; замовлення: ' + cartinfo + '; коментарій: ' + \
                      str(orderform.cleaned_data['clientcomment']) + '; загальна сумма замовлення: ' + str(cart.get_total_price()) + ' грн.'

            recipients = ['avi.upsale@gmail.com']

            try:
                send_mail(username, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('something goes wrong ;(')
            if not request.user.is_authenticated():
                cart.clear()
                return HttpResponseRedirect('/complete')
            else:
                formsave = form.save(commit=False)
                formsave.user =user
                for item in cart:
                    GoodPay.objects.create(user=user,
                                           prises=item['prise'],
                                           price=item['good_price'],
                                           quantity=item['quantity'],
                                           ordersum=int(item['good_price'])*item['quantity']
                                           )
                cart.clear()
                return HttpResponseRedirect('/complete')


    else:
        orderform = OrderForm()
        form =  PayGoodForm()
    return render(request, 'magaz/of.html', {'orderform': orderform, 'cart': cart, 'form': form})
"""
    if request.method == 'POST':
        cabinet_form = CabinetForm(request.POST)
        user = User.objects.get(pk=request.user.id)

        if cabinet_form.is_valid():
            profile = cabinet_form.save(commit=False)
            profile.user = user

            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']
            profile.save()
        else:
            print(cabinet_form.errors)
    else:
        cabinet_form = CabinetForm()
"""

magaz/templates/magaz/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
  <head>
  <title>{% block title %}{% endblock %}</title>

      <meta charset="utf-8">
      <meta content="IE=edge" http-equiv="X-UA-Compatible">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

        <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/united/bootstrap.min.css" rel="stylesheet">
        <link href="{% static 'blog/style.css' %}" rel="stylesheet">
        <link href="{% static 'blog/favicon.ico' %}" rel="shortcut icon">

        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
          <script type="text/javascript">

$(function() {

$(window).scroll(function() {

if($(this).scrollTop() != 0) {

$('#toTop').fadeIn();

} else {

$('#toTop').fadeOut();

}

});

$('#toTop').click(function() {

$('body,html').animate({scrollTop:0},800);

});

});

</script>
  </head>

  <body class="full">

<DIV ID = "toTop" > ↑ Up ↑</DIV >
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '875647719207539',
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

  <script id="dsq-count-scr" src="//sferalaser.disqus.com/count.js" async></script>


    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Sfera-Laser</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
             <div class="nav pull-right" id="nav_log">
            {% if user.is_authenticated %}
                 <div class="navbar-text navbar-right" id="usermoveup">Ви увійшли, як  <strong>{% firstof user.get_short_name user.get_username %}</strong>
                 {% if user.avataruser.avatar  %}
                 <img src="{{ user.avataruser.avatar.url }}" width="30" id="userpic">
                 {% else %}
                 <img src="{% static 'blog/default_user.png' %}" width="30" id="userpic">
                 {% endif %}
                 </div>

                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    <div id="carthead" class="nav pull-right">
                    <a href="{% url "cart1:cart_detail" %}">
                    <span class="glyphicon glyphicon-shopping-cart" id="carticon">{{ total_items }}</span>
                    </a>
                 {% if val.userdata.valute == 'usd' %}
                     на {{ cart.get_dolar_total_price }} $
                 {% else %}
                     на {{ cart.get_total_price }} Грн
                 {% endif %}
                    </div>
                {% else %}
                    <div id="carthead" class="nav pull-right">
                    <span class="glyphicon glyphicon-shopping-cart" id="carticon"></span>
                    </div>
                {% endif %}
                {% endwith %}
            {% else %}
                <div class="navbar-text navbar-right" id="usermoveup">Ви не авторизовані
                <img src="{% static 'blog/default_user.png' %}" width="30" id="userpic">
                </div>
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    <div id="carthead" class="nav pull-right">
                    <a href="{% url "cart1:cart_detail" %}">
                        <span class="glyphicon glyphicon-shopping-cart" id="carticon"></span>
                        {{ total_items }}
                    </a>
                 {% if val.userdata.valute == 'usd' %}
                     на {{ cart.get_dolar_total_price }} $
                 {% else %}
                     на {{ cart.get_total_price }} Грн
                 {% endif %}
                    </div>
                {% else %}
                    <div id="carthead" class="nav pull-right">
                    <span class="glyphicon glyphicon-shopping-cart" id="carticon"></span>
                    </div>
                {% endif %}
                {% endwith %}
            {% endif %}

        {% if 'shop' in request.path or 'cart' in request.path %}
        <form class="form-inline pull-right" action="{% url 'set_usd' %}" method="get" >
            {% csrf_token %}

            <input type="hidden" name="next" value="{{ request.path }}">
            {% if val.userdata.valute == 'usd'%}
                <input type="submit" value="usd" class="btn btn-default btn-xs" id="valutebuttonactive" />
            {% else %}
                <input type="submit" value="usd" class="btn btn-default btn-xs" id="valutebutton" />
            {% endif %}
        </form>

        <form class="form-inline pull-right" action="{% url 'set_uah' %}" method="get" >
            {% csrf_token %}
            {{ hrivra_form }}
            <input type="hidden" name="next" value="{{ request.path }}">
                   {% if val.userdata.valute == 'uah'%}
                <input type="submit" value="uah" class="btn btn-default btn-xs" id="valutebuttonactive" />
            {% else %}
                <input type="submit" value="uah" class="btn btn-default btn-xs" id="valutebutton" />
            {% endif %}
        </form>
        {% endif %}
          </div>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Головна</a></li>
            <li><a href="{% url 'about' %}">Контакти</a></li>
            <li><a href="{% url 'xxx' %}">Блог</a> </li>
            <li><a href="/photologue/">Галерея</a> </li>
            <li><a href="/shop/">Магазин</a> </li>
            {% if user.is_authenticated %}
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Профіль <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    <li><a href="{% url 'cabinet' %}">Ососбистий кабінет</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'logout' %}">Вихід</a></li>
              </ul>

              {% else %}
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Вхід <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'userlogin' %}">Вхід</a></li>
                <li><a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Вхід через FaceBook</a></li>
                <li class="divider"></li>
                <li><a href="/register"> Реєстрація</a></li>
              </ul>
            </li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container main-content ">
    {% autoescape off %}
        {% block content %}
        {% endblock %}
    {% endautoescape %}

    </div><!-- /.container -->

      <div class="foot mas" >
      <footer>
        &copy; 2016 Зроблено на Сихові &middot; <a href="https://www.facebook.com/profile.php?id=100007905615689">Андрій Війтик</a> &middot; <a href="https://www.facebook.com/SferaLaser">Сфера-Лазер</a>
      </footer>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  </body>
</html>

magaz/templates/magaz/cat_detail.html
{% extends 'magaz/base.html' %}
{% block title %}
    {{ category.cat_name }}
{% endblock %}

{% block content %}
<h1>{{ category.cat_name }}</h1>
<hr>
{% for prises in category.prises_set.all  %}
        <div class="row col-lg-6">
             <div class="shop-pr">
                <h5 id="good_link"><a href="{% url 'prises' prises.id %}">{{ prises.good_name }}</a></h5>
                <img src="{{ prises.pic.url }}" id="good_pic">
                <p>{{ prises.shortMagazText }}</p>
                 {% if val.userdata.valute == 'usd' %}
                        <p>{{ prises.get_dolar }} $</p>
                 {% else %}
                     <p>{{ prises.good_price }} Грн.</p>
                 {% endif %}

                <a class="btn btn-default" id="cat_btn1" href="{% url 'prises' prises.id %}" role="button"> Купити </a>
             </div>
        </div>
{% endfor %}
{% endblock %}

magaz/templates/magaz/good.html
<!DOCTYPE html>
<html>
{% extends 'magaz/base.html' %}
<head lang="en">
    <meta charset="UTF-8">
    {% block title %}{{ prices.good_name }}{% endblock %}
</head>
<body>
{% block content %}
    <div class="onegood">
     <h4 id="new_product">{{ prices.good_name }}</h4>
     <img src="{{ prices.pic.url }}" id="one_pic">
      <h4>{{ prices.good_about }}</h4>
    {% if val.userdata.valute == 'usd' %}
        <h4 id="price_hot">{{ prices.get_dolar }} $</h4>
    {% else %}
        <h4 id="price_hot">{{ prices.good_price }} Грн.</h4>
    {% endif %}
    {% if prices.in_magaz %}
        <p id="in_magaz"> є в наявності</p>
    {% else  %}
        <p id="in_magaz"> передзамовлення</p>
    {% endif %}
    <hr>
        <form action="{% url "cart1:cart_add" prices.id %}" method="post" class="form-inline">
             <div class="form-group">
            {{ cart_product_form }}
            {% csrf_token %}
             </div>
            <input type="submit" value="Додати в кошик" class="btn btn-primary btn-sm">
        </form>
    <hr>

    </div>
{% endblock %}
</body>
</html>

magaz/templates/magaz/of.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form method="post" action="{% url 'of' %}">
        {% csrf_token %}
        {{ orderform }}
        {{ form }}
        <input type="submit" value="Відправити"/>
    </form>
</body>
</html>

magaz/templates/magaz/order.html
{% extends 'magaz/base.html' %}
{% block content %}
<h1>Оформлення замовлення</h1>
     <table class="order"  >

        <tbody>
        {% for item in cart %}
            {% with prise=item.prise %}
            <tr>
                <td>{{ prise.good_name }}</td>
                <td>{{ item.quantity }} Шт</td>
                <td>{{ item.good_price }} Грн</td>
            </tr>
            {% endwith %}

        {% endfor %}
        <tr>
            <td>Загална сумма</td>
            <td colspan="1"></td>
            <td >{{ cart.get_total_price }} Грн</td>
        </tr>
        </tbody>
    </table>
    <div id="simpleformorder" >
        <form method="post" action="{% url 'of' %}" class="form-horizontal" id="orderform">
        {% csrf_token %}
            <div class="form-group">
	            <label for="id_clientname" > Ім'я &#42;</label>
	            {{ of.clientname }}
            </div>

            <div class="form-group">
	            <label for="id_clientsorganization" > Организація</label>
	            {{ of.clientsorganization }}
            </div>

            <div class="form-group">
	            <label for="id_clientsnumb" > Номер телефону &#42;</label>
	            {{ of.clientsnumb }}
            </div>

            <div class="form-group">
	            <label for="id_clientmail" > E-mail</label>
	            {{ of.clientmail }}
            </div>

            <div class="form-group">
	            <label for="id_clientdevelop" > Спосіб доставки</label>
	            {{ of.clientdevelop }}
            </div>

            <div class="form-group">
	            <label for="clientcomment" > Коментарій до замовлення</label>
	            {{ of.clientcomment }}
            </div>


        <input type="submit" value="Відправити"/>
        </form>
    <p>&#42; - поля, обов'язкові для заповнення</p>
    </div>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'order' %}">
            {{ form }}
            </form>
            {% endif %}


{% endblock %}

magaz/templates/magaz/shop1.html
{% extends 'magaz/base.html' %}
{% load staticfiles %}
{% block title %}LASER_SHOP{% endblock %}
{% block content %}
<h1> Категорії товарів </h1>
    <hr>
     {% for category in categories %}

        <div class="row col-lg-3">
             <div class="shop">
                <img src="{{ category.cat_pic.url }}" id="shop_pic">
                 <p><a class="btn btn-default" id="cat_btn" href="{% url 'category' category.slag_url %}" role="button">{{ category.cat_name }} </a></p>
             </div>
        </div>

    {% endfor %}

{% endblock %}